### ISSUE TITLE
I buy course

### ISSUE THREAD

**Issue by Dazmed707** [simplerhacking/Evilginx3-Phishlets#1]
Available phishlet for google for students ?

**Comment by simplerhacking** [comment]
Been working on it for the past month... You don't understand how fucking complex & tedious it is to get this one to work consistently with no errors. I'll probably upload it to the private group once I trim it down and also bypass the double 2fa challenge. 

If u want to be notified when I upload it, join the email list on www.simplerhacking.com

![Google Phishlet V1](https://github.com/simplerhacking/Evilginx3-Phishlets/assets/141525149/e6988d29-5538-4b58-98be-b656c71ad67e)

**Comment by Dazmed707** [comment]
I have Google Phishlet Available.
![image](https://github.com/simplerhacking/Evilginx3-Phishlets/assets/35184132/c07cc2d1-f699-4397-912f-b58cd891b156)

**Comment by Dazmed707** [comment]
Google phishlet done ?
![image](https://github.com/simplerhacking/Evilginx3-Phishlets/assets/35184132/9ea6e364-d289-4ae2-aa7e-bce2115aece4)

**Comment by Dazmed707** [comment]
can you send the google phishlet to those who bought the course ?

**Comment by Johnnycage7734** [comment]
Did he send it?

**Comment by simplerhacking** [comment]
@Dazmed707 My above message already states that I will upload it when it is ready. I do not want to upload something that works for 2 weeks then is no longer supported if a slight auth protocol change gets made.

**Comment by simplerhacking** [comment]
@Dazmed707

.. Saw your message. 

How about send an email to our support email info@simplerhacking.com so we can help you vs opening an issue on Github about our evilginx3 phishlets. The support email inbox has 0 emails from you or your accounts. Our support email is public on all platforms, all resources and advertised vehemently on every page so any student can reach out to us for any questions or concerns. Seriously mark.

**Comment by Dazmed707** [comment]
THANK YOU, YOU HELPED ME IN SUPPORT, I PURCHASED THE COURSE WITH ANOTHER EMAIL

I HAVE ANOTHER QUESTION, HOW CAN I PREVENT MESSAGES FROM GOING TO SPAM?

![image](https://github.com/simplerhacking/Evilginx3-Phishlets/assets/35184132/565af7ce-3c7c-46d8-ace0-779e9bb1c3a1)


I USE GOPHISH FOR SEND MAILS

**Comment by Dazmed707** [comment]
@Johnnycage7734 SEND ME TEXT TO TELEGRAM IF U NEED GOOGLE PHISHLET

@NDLR7
