### ISSUE TITLE
Can anyone tell me how to load these into evilginx3 ? 

### ISSUE THREAD

**Issue by Johnnycage7734** [simplerhacking/Evilginx3-Phishlets#5]
I’ve been trying to get these to start up into my evilginx3 for a few days now. This isn’t a coding issue from simplerhacking btw, I just don’t know how to lead the phishlets in. I’m using powershell on windows. I can get evilginx3 up and running just fine. Just need to add these phishlets. Can anyone give me any suggestions on what command to run to get these in my Evilginx? 
/

**Comment by john-whick-13** [comment]
Do you have google or facebook phishlets

**Comment by Johnnycage7734** [comment]
I have neither. I have the bare evilgin3 with no phishlets. Just wanna get these loaded on

**Comment by Johnnycage7734** [comment]
Solved

**Comment by lurod1** [comment]
what did u do?

**Comment by lurod1** [comment]
what did u do?

@Johnnycage7734
