### ISSUE TITLE
Your Evilginx professional course is great thx!

### ISSUE THREAD

**Issue by Beloha2e** [simplerhacking/Evilginx3-Phishlets#9]
Hi, @simplerhacking  I just wanted to let know that I appreciate you creating a quality affordable option for Evilginx education!

And also do you have a place where I can watch your recorded live webinars? I missed the one you did on Monday on SpearPhishing with AI & machine Learning. My current timezone is not USA so its hard to catch them live.

**Comment by simplerhacking** [comment]
@Beloha2e I will upload a couple webinar replys like the one on Evilginx3 SpearPhishing Linkedin 2fa authentication & EvilVNC later this month. I will do another 1 soon but those just sort of take a while to setup bc I try to make them fairly interesting and not boring ash in PPT. I did upload the webinar materials in the resources section on simplerhacking tho so you can find the materials there just not the full recorded stream & Q&A. The evilginx3 Linkedin phishlet script is there as well in the pro course resources section if you want to download or tweak it.

**Comment by simplerhacking** [comment]
@Beloha2e I uploaded everything here on SimplerHacking.com :)

![Course Addons Section](https://github.com/simplerhacking/Evilginx3-Phishlets/assets/141525149/afeee662-f721-45c0-903c-1adcac94bc1d)
